"""CLI contract constants and compatibility exports for procurement packages."""
from __future__ import annotations

from app.services.procurement_decision_package.package_constants import (  # noqa: F401
    ARTIFACT_INVENTORY_TABLE_BODY_OFFSET,
    ARTIFACT_INVENTORY_TABLE_HEADER,
    ARTIFACT_INVENTORY_TABLE_SEPARATOR,
    AUDIT_MANIFEST_ARTIFACT_GROUPS,
    AUDIT_MANIFEST_FIELD_ORDER,
    AUDIT_MANIFEST_NAME,
    AUDIT_MANIFEST_PACKET_STATUS,
    AUDIT_MANIFEST_SCHEMA_PURPOSE,
    BID_READINESS_CHECKLIST_FIELD_ORDER,
    BID_READINESS_CHECKLIST_NAME,
    BID_SUBMISSION_ACTION,
    DECISION_PACKAGE_DOCUMENT_PATH,
    DECISION_PACKAGE_FIELD_ORDER,
    DECISION_PACKAGE_NAME,
    DECISION_PACKAGE_ROOT_PATH,
    DECISION_PACKAGE_TOP_LEVEL_FIELD_ORDER,
    DECISION_SUMMARY_NAME,
    DEFAULT_DEMO_DATA_DIR,
    DEFAULT_DEMO_OUT_DIR,
    DEMO_EVIDENCE_CHECK_FIELDS,
    DEMO_RECEIPT_NAME,
    DEMO_RECEIPT_REQUIRED_MARKERS,
    DEMO_RECEIPT_VALIDATION_SUMMARY_FIELDS,
    DEMO_RECOMMENDATION,
    DEMO_RESULT_NAME,
    DEMO_PROJECT_ID,
    DEMO_TENANT_ID,
    EVIDENCE_SUMMARY_FIELD_ORDER,
    EVIDENCE_SUMMARY_NAME,
    EVIDENCE_SUMMARY_REQUIRED_MARKERS,
    EXCLUDED_ACTION_ORDER,
    EXPECTED_DECISION_PACKAGE_SCHEMA_PURPOSE,
    EXPLICIT_AUTHORIZATION_BOUNDARY,
    EXPORT_MANIFEST_FIELD_ORDER,
    EXPORT_MANIFEST_NAME,
    EXTERNAL_RUNTIME_ACTION_ORDER,
    GATE_NAME,
    GATE_RESULT_NAME,
    HARD_FILTER_FIELD_ORDER,
    INCLUDED_ARTIFACT_ORDER,
    JSON_ARTIFACT_PACKAGE_FIELDS,
    LOCAL_DEMO_CLI_CONTRACT_MANIFEST_PATH,
    LOCAL_DEMO_EXPECTED_PACKAGE_PATH,
    LOCAL_DEMO_SAMPLE_DIR,
    LOCAL_DEMO_SAMPLE_INPUT_PATH,
    LOCAL_DEMO_SCENARIO_ID,
    NEXT_REVIEW_ACTION_WITH_GAPS,
    NON_APPROVAL_MARKER,
    NON_AUTHORIZATION_MARKER,
    NON_AUTHORIZATION_NOTE,
    OPPORTUNITY_REF_FIELD_ORDER,
    PACKAGE_CHECKLIST_STATUSES,
    PACKAGE_DOCUMENT_VALIDATION_PATH,
    PACKAGE_EVIDENCE_TYPES,
    PACKAGE_HARD_FILTER_STATUSES,
    PACKAGE_SOFT_FIT_BANDS,
    PENDING_SIGNOFF_FIELD_ORDER,
    PENDING_SIGNOFF_NAME,
    PROCUREMENT_DECISION_PACKAGE_SAMPLE_VALIDATION_SCHEMA_PURPOSE,
    PROCUREMENT_DECISION_PACKAGE_SCHEMA_PURPOSE,
    PROCUREMENT_REVIEW_NAME,
    PROPOSAL_HANDOFF_FIELD_ORDER,
    PROPOSAL_HANDOFF_NAME,
    PROPOSAL_HANDOFF_SCOPE,
    PROVIDER_API_EXECUTION_ACTION,
    RECOMMENDATIONS,
    REVIEWER_HANDOFF_FIELD_ORDER,
    REVIEWER_HANDOFF_NAME,
    SCOPED_REVIEW_MARKER,
    SIGNOFF_SCOPE,
    SIGNOFF_SUMMARY_NAME,
    SMOKE_CHECK_NAME,
    SMOKE_CHECK_RESULT_NAME,
    SMOKE_NAME,
    SMOKE_RESULT_NAME,
    SOFT_FIT_FACTOR_FIELD_ORDER,
    SOFT_FIT_SCORE_FIELD_ORDER,
    VALIDATION_SUMMARY_FIELD_ORDER,
    VALIDATION_SUMMARY_NAME,
    _DemoReceiptContext,
    _DemoReceiptValidationSummary,
    _PackageIdentity,
    _SmokeEvidenceContext,
    _SmokeEvidencePaths,
    _SYSTEM_TEMP_DIR,
)


CLI_CONTRACT_MANIFEST_SCHEMA_PURPOSE = (
    "procurement_decision_package_cli_contract_manifest"
)
CLI_CONTRACT_MANIFEST_CONTRACT_VERSION = "1.3.0"
CLI_CONTRACT_MANIFEST_WORKFLOW = "procurement_decision_package_local_demo"
CLI_CONTRACT_MANIFEST_CONTRACT_STATUS = "local_only"
CLI_CONTRACT_MANIFEST_IDENTITY_VALUES = (
    ("schema_purpose", CLI_CONTRACT_MANIFEST_SCHEMA_PURPOSE),
    ("contract_version", CLI_CONTRACT_MANIFEST_CONTRACT_VERSION),
    ("workflow", CLI_CONTRACT_MANIFEST_WORKFLOW),
    ("contract_status", CLI_CONTRACT_MANIFEST_CONTRACT_STATUS),
)
CLI_CONTRACT_MANIFEST_VALIDATION_RESULT_NAME = (
    "cli_contract_manifest_validation_result.json"
)
CLI_CONTRACT_MANIFEST_VALIDATION_CHECK_NAME = (
    "procurement_decision_package_cli_contract_manifest_result"
)
CLI_CONTRACT_MANIFEST_VALIDATION_CHECK_RESULT_NAME = (
    "cli_contract_manifest_validation_check_result.json"
)
CLI_CONTRACT_MANIFEST_FIELDS = (
    "schema_purpose",
    "contract_version",
    "workflow",
    "contract_status",
    "stdout_json_contract",
    "external_actions_excluded",
    "cli_contracts",
)
CLI_CONTRACT_MANIFEST_STDOUT_CONTRACT_FIELDS = ("success", "handled_failure")
CLI_CONTRACT_MANIFEST_STDOUT_SUCCESS_FIELDS = (
    "exit_code",
    "status",
    "forbidden_fields",
)
CLI_CONTRACT_MANIFEST_STDOUT_FAILURE_FIELDS = ("exit_code", "status", "required_fields")
CLI_CONTRACT_MANIFEST_CLI_CONTRACT_FIELDS = (
    "case_name",
    "script",
    "success_required_fields",
    "failure_required_fields",
)
CLI_CONTRACT_MANIFEST_VALIDATION_RESULT_FIELDS = (
    "schema_purpose",
    "contract_version",
    "status",
    "manifest_path",
    "manifest_sha256",
    "manifest_size_bytes",
    "workflow",
    "contract_status",
    "contract_count",
    "script_count",
    "case_names",
    "scripts",
    "external_actions_excluded",
    "success_required_fields_by_case",
    "failure_required_fields_by_case",
    "cli_contract_fingerprint",
)
CLI_CONTRACT_MANIFEST_VALIDATION_CHECK_FIELDS = (
    "check",
    "status",
    "validation_result_path",
    "manifest_path",
    "contract_version",
    "manifest_sha256",
    "manifest_size_bytes",
    "workflow",
    "contract_status",
    "contract_count",
    "script_count",
    "case_names",
    "scripts",
    "external_actions_excluded",
    "success_required_fields_by_case",
    "failure_required_fields_by_case",
    "cli_contract_fingerprint",
    "validation_result_checked",
)
CLI_CONTRACT_MANIFEST_VALIDATION_CHECK_FAILURE_FIELDS = (
    "status",
    "check",
    "validation_result_path",
    "error_type",
    "error",
)
CLI_CONTRACT_MANIFEST_VALIDATION_FAILURE_FIELDS = (
    "schema_purpose",
    "contract_version",
    "status",
    "manifest_path",
    "error_type",
    "error",
)
CLI_CONTRACT_MANIFEST_CASE_MAP_FIELDS = (
    "success_required_fields_by_case",
    "failure_required_fields_by_case",
)
CLI_CONTRACT_MANIFEST_CURRENT_VALIDATION_MATCH_FIELDS = (
    "schema_purpose",
    "contract_version",
    "workflow",
    "contract_status",
    "contract_count",
    "script_count",
    "case_names",
    "scripts",
    "external_actions_excluded",
    "success_required_fields_by_case",
    "failure_required_fields_by_case",
    "cli_contract_fingerprint",
    "manifest_sha256",
    "manifest_size_bytes",
)
CLI_CONTRACT_MANIFEST_CURRENT_VALIDATION_FIELDS = (
    "contract_version",
    "manifest_sha256",
    "manifest_size_bytes",
    "workflow",
    "contract_status",
    "contract_count",
    "script_count",
    "case_names",
    "scripts",
    "external_actions_excluded",
    "success_required_fields_by_case",
    "failure_required_fields_by_case",
    "cli_contract_fingerprint",
)
CLI_CONTRACT_MANIFEST_CASE_ORDER = (
    "sample_validator",
    "sample_builder",
    "artifact_checker",
    "packet_manager",
    "review_receipt_manager",
    "reviewed_package_manager",
    "demo_runner",
    "project_export",
    "evidence_gate",
    "smoke_wrapper",
    "smoke_checker",
    "cli_contract_manifest_validator",
    "cli_contract_manifest_result_checker",
)
CLI_CONTRACT_MANIFEST_CASE_NAMES = set(CLI_CONTRACT_MANIFEST_CASE_ORDER)
CLI_CONTRACT_MANIFEST_CASE_SCRIPTS = {
    "sample_validator": "scripts/validate_procurement_decision_package_sample.py",
    "sample_builder": "scripts/build_procurement_decision_package_sample.py",
    "artifact_checker": "scripts/check_procurement_decision_package_artifacts.py",
    "packet_manager": "scripts/manage_procurement_decision_review_packet.py",
    "review_receipt_manager": "scripts/manage_procurement_review_receipt.py",
    "reviewed_package_manager": "scripts/manage_procurement_reviewed_package.py",
    "demo_runner": "scripts/run_procurement_decision_package_demo.py",
    "project_export": "scripts/export_procurement_decision_package.py",
    "evidence_gate": "scripts/gate_procurement_decision_package_demo.py",
    "smoke_wrapper": "scripts/smoke_procurement_decision_package_demo_gate.py",
    "smoke_checker": "scripts/check_procurement_decision_package_smoke_result.py",
    "cli_contract_manifest_validator": (
        "scripts/validate_procurement_decision_package_cli_contract_manifest.py"
    ),
    "cli_contract_manifest_result_checker": (
        "scripts/check_procurement_decision_package_cli_contract_manifest_result.py"
    ),
}
CLI_CONTRACT_MANIFEST_GLOBAL_FAILURE_FIELDS = ("status", "error_type", "error")
CLI_CONTRACT_MANIFEST_GLOBAL_SUCCESS_FORBIDDEN_FIELDS = ("error", "error_type")
CLI_CONTRACT_MANIFEST_SUCCESS_FIELDS_BY_CASE = {
    "sample_validator": (
        "schema_purpose",
        "status",
        "sample_input",
        "expected_package",
        "scenario_id",
        "recommendation",
        "authorization_boundary",
    ),
    "sample_builder": (
        "schema_purpose",
        "status",
        "output_dir",
        "artifacts",
        "recommendation",
        "authorization_boundary",
    ),
    "artifact_checker": (
        "status",
        "output_dir",
        "artifact_count",
        "recommendation",
        "authorization_boundary",
        "operational_approval",
        *DEMO_EVIDENCE_CHECK_FIELDS,
    ),
    "packet_manager": (
        "status",
        "operation",
        "source_dir",
        "packet_path",
        "packet_sha256",
        "packet_size_bytes",
        "schema_version",
        "package_id",
        "recommendation",
        "artifact_count",
        "entry_count",
        "authorization_boundary",
        "operational_approval",
        "packet_verified",
    ),
    "review_receipt_manager": (
        "status",
        "operation",
        "packet_path",
        "receipt_path",
        "receipt_sha256",
        "receipt_size_bytes",
        "receipt_schema_version",
        "review_status",
        "packet_sha256",
        "package_id",
        "recommendation",
        "reviewer",
        "decision",
        "reviewed_at",
        "authorization_boundary",
        "operational_approval",
        "receipt_valid",
    ),
    "reviewed_package_manager": (
        "status",
        "operation",
        "source_packet_path",
        "receipt_path",
        "package_path",
        "package_sha256",
        "package_size_bytes",
        "schema_version",
        "reviewed_package_status",
        "package_id",
        "recommendation",
        "reviewer",
        "decision",
        "reviewed_at",
        "entry_count",
        "authorization_boundary",
        "operational_approval",
        "package_verified",
    ),
    "demo_runner": (
        "status",
        "schema_purpose",
        "output_dir",
        "demo_tenant_id",
        "demo_project_id",
        "seeded_decision_id",
        "demo_result_path",
        "demo_receipt_path",
        "artifact_check",
        "artifact_inventory",
        "artifacts",
        "tenant_id",
        "project_id",
        "decision_id",
        "recommendation",
        "authorization_boundary",
        "clean_output",
    ),
    "project_export": (
        "status",
        "schema_purpose",
        "tenant_id",
        "project_id",
        "decision_id",
        "output_dir",
        "artifacts",
        "recommendation",
        "authorization_boundary",
    ),
    "evidence_gate": (
        "status",
        "gate",
        "output_dir",
        "demo_result_path",
        "demo_receipt_path",
        "operational_approval",
        "artifact_count",
        "excluded_external_actions",
        "recommendation",
        "authorization_boundary",
        "artifacts",
        *DEMO_EVIDENCE_CHECK_FIELDS,
    ),
    "smoke_wrapper": (
        "status",
        "smoke",
        "output_dir",
        "demo_result_path",
        "gate_result_path",
        "smoke_result_path",
        "smoke_check_result_path",
        "evidence_files",
        "operational_approval",
        "data_dir",
        "demo_tenant_id",
        "demo_project_id",
        "seeded_decision_id",
        "demo_receipt_path",
        "gate_result_written",
        "smoke_result_written",
        "smoke_check_result_written",
        "package_artifacts_checked",
        "smoke_result_checked",
        *DEMO_EVIDENCE_CHECK_FIELDS,
        "artifact_count",
        "excluded_external_actions",
        "recommendation",
        "authorization_boundary",
        "clean_output",
    ),
    "smoke_checker": (
        "status",
        "check",
        "smoke_result_path",
        "output_dir",
        "package_artifacts_checked",
        "smoke_result_checked",
        "evidence_files",
        "smoke_check_result_path",
        "smoke_check_result_written",
        "demo_tenant_id",
        "demo_project_id",
        "seeded_decision_id",
        "artifact_count",
        "excluded_external_actions",
        "recommendation",
        "authorization_boundary",
        "operational_approval",
        "clean_output",
    ),
    "cli_contract_manifest_validator": CLI_CONTRACT_MANIFEST_VALIDATION_RESULT_FIELDS,
    "cli_contract_manifest_result_checker": CLI_CONTRACT_MANIFEST_VALIDATION_CHECK_FIELDS,
}
CLI_CONTRACT_MANIFEST_FAILURE_FIELDS_BY_CASE = {
    "sample_validator": (
        "schema_purpose",
        "status",
        "sample_input",
        "expected_package",
        "error_type",
        "error",
    ),
    "sample_builder": (
        "schema_purpose",
        "status",
        "sample_input",
        "output_dir",
        "error_type",
        "error",
    ),
    "artifact_checker": ("status", "output_dir", "error_type", "error"),
    "packet_manager": (
        "status",
        "operation",
        "source_dir",
        "packet_path",
        "error_type",
        "error",
    ),
    "review_receipt_manager": (
        "status",
        "operation",
        "packet_path",
        "receipt_path",
        "error_type",
        "error",
    ),
    "reviewed_package_manager": (
        "status",
        "operation",
        "source_packet_path",
        "receipt_path",
        "package_path",
        "error_type",
        "error",
    ),
    "demo_runner": (
        "schema_purpose",
        "status",
        "data_dir",
        "output_dir",
        "clean_output",
        "error_type",
        "error",
    ),
    "project_export": (
        "status",
        "schema_purpose",
        "data_dir",
        "tenant_id",
        "project_id",
        "output_dir",
        "error_type",
        "error",
    ),
    "evidence_gate": (
        "status",
        "gate",
        "output_dir",
        "error_type",
        "error",
    ),
    "smoke_wrapper": (
        "status",
        "smoke",
        "data_dir",
        "output_dir",
        "clean_output",
        "gate_result_path",
        "smoke_result_path",
        "smoke_check_result_path",
        "evidence_files",
        "gate_result_written",
        "smoke_result_written",
        "smoke_check_result_written",
        "package_artifacts_checked",
        "smoke_result_checked",
        "error_type",
        "error",
    ),
    "smoke_checker": (
        "check",
        "status",
        "smoke_result_path",
        "error_type",
        "error",
    ),
    "cli_contract_manifest_validator": CLI_CONTRACT_MANIFEST_VALIDATION_FAILURE_FIELDS,
    "cli_contract_manifest_result_checker": (
        CLI_CONTRACT_MANIFEST_VALIDATION_CHECK_FAILURE_FIELDS
    ),
}
EVIDENCE_FILE_FIELDS = (
    "demo_result",
    "demo_receipt",
    "gate_result",
    "smoke_result",
    "smoke_check_result",
)
SMOKE_EVIDENCE_PATH_FIELDS = (
    ("demo_result_path", "demo_result"),
    ("demo_receipt_path", "demo_receipt"),
    ("gate_result_path", "gate_result"),
    ("smoke_result_path", "smoke_result"),
    ("smoke_check_result_path", "smoke_check_result"),
)
SMOKE_PACKAGE_ARTIFACT_MATCH_FIELDS = (
    "recommendation",
    "authorization_boundary",
    "operational_approval",
    "artifact_count",
    *DEMO_EVIDENCE_CHECK_FIELDS,
)
SMOKE_DEMO_IDENTITY_FIELDS = (
    "demo_tenant_id",
    "demo_project_id",
    "seeded_decision_id",
)
SMOKE_DEMO_CONTEXT_FIELDS = (
    "output_dir",
    "clean_output",
)
SMOKE_DEMO_RESULT_MATCH_FIELDS = (
    "recommendation",
    "authorization_boundary",
)
SMOKE_DEMO_ARTIFACT_CHECK_FIELDS = (
    "operational_approval",
    *DEMO_EVIDENCE_CHECK_FIELDS,
)
SMOKE_REQUIRED_FALSE_FIELDS = (
    "operational_approval",
)
SMOKE_REQUIRED_TRUE_FIELDS = (
    "gate_result_written",
    "smoke_result_written",
    *DEMO_EVIDENCE_CHECK_FIELDS,
)
SMOKE_CHECK_CONTEXT_FIELDS = (
    "smoke_check_result_written",
    "demo_tenant_id",
    "demo_project_id",
    "seeded_decision_id",
    "artifact_count",
)
SMOKE_CHECK_DECISION_FIELDS = (
    "recommendation",
    "authorization_boundary",
)
DEFAULT_DECISION_PACKAGE_OUTPUT_BASE = _SYSTEM_TEMP_DIR / "decisiondoc-procurement-decision-packages"
PROPOSAL_ALLOWED_NEXT_STEPS = [
    "prepare proposal outline",
    "assign evidence owner",
    "confirm reviewer sign-off",
]
SIGNOFF_SUMMARY_REQUIRED_MARKERS = [
    "Status: `pending`",
    f"Scope: `{SIGNOFF_SCOPE}`",
    "Operational approval: `false`",
    NON_AUTHORIZATION_MARKER,
]
