#!/usr/bin/env python3
from __future__ import annotations

import argparse
import os
import secrets
from pathlib import Path
from typing import Sequence


REPO_ROOT = Path(__file__).resolve().parents[1]
TEMPLATE_DIR = REPO_ROOT / "docs" / "deployment" / "env_templates"
PROFILE_TEMPLATES = {
    "admin": TEMPLATE_DIR / "admin.env",
    "dawool": TEMPLATE_DIR / "dawool.env",
}
PROFILE_ORIGINS = {
    "admin": "https://admin.decisiondoc.kr",
    "dawool": "https://dawool.decisiondoc.kr",
}


def _load_env_lines(path: Path) -> list[tuple[str, str]]:
    resolved = Path(path).expanduser()
    if not resolved.exists():
        raise SystemExit(f"Template env file not found: {resolved}")
    loaded: list[tuple[str, str]] = []
    for lineno, raw_line in enumerate(resolved.read_text(encoding="utf-8").splitlines(), start=1):
        line = raw_line.strip()
        if not line or line.startswith("#"):
            continue
        if "=" not in line:
            raise SystemExit(f"Invalid env template line {lineno}: {resolved}")
        key, value = line.split("=", 1)
        normalized_key = key.strip()
        if not normalized_key:
            raise SystemExit(f"Invalid env template line {lineno}: {resolved}")
        loaded.append((normalized_key, value.strip()))
    return loaded


def _resolve_openai_key(explicit_value: str) -> str:
    normalized = str(explicit_value or "").strip()
    if normalized:
        return normalized
    env_value = os.getenv("OPENAI_API_KEY", "").strip()
    if env_value:
        return env_value
    raise SystemExit(
        "Missing OpenAI API key. Pass --openai-api-key or set OPENAI_API_KEY in the shell."
    )


def _render_profile_env(
    *,
    profile: str,
    openai_api_key: str,
    origin: str,
    jwt_secret: str,
    api_key: str,
    ops_key: str,
) -> str:
    template_path = PROFILE_TEMPLATES[profile]
    lines = _load_env_lines(template_path)
    replacements = {
        "JWT_SECRET_KEY": jwt_secret,
        "ALLOWED_ORIGINS": origin,
        "DECISIONDOC_API_KEYS": api_key,
        "DECISIONDOC_OPS_KEY": ops_key,
        "OPENAI_API_KEY": openai_api_key,
    }
    rendered: list[str] = []
    for key, value in lines:
        rendered.append(f"{key}={replacements.get(key, value)}")
    return "\n".join(rendered) + "\n"


def bootstrap_prod_env(
    *,
    profile: str,
    output_file: Path,
    openai_api_key: str,
    origin: str = "",
    jwt_secret: str = "",
    api_key: str = "",
    ops_key: str = "",
    force: bool = False,
) -> Path:
    normalized_profile = str(profile or "").strip().lower()
    if normalized_profile not in PROFILE_TEMPLATES:
        raise SystemExit(f"profile must be one of: {', '.join(sorted(PROFILE_TEMPLATES))}")

    resolved_output = Path(output_file).expanduser()
    if resolved_output.exists() and not force:
        raise SystemExit(f"Output file already exists: {resolved_output}. Pass --force to overwrite.")

    resolved_origin = str(origin or "").strip() or PROFILE_ORIGINS[normalized_profile]
    resolved_openai_key = _resolve_openai_key(openai_api_key)
    resolved_jwt_secret = str(jwt_secret or "").strip() or secrets.token_hex(32)
    resolved_api_key = str(api_key or "").strip() or secrets.token_hex(32)
    resolved_ops_key = str(ops_key or "").strip() or secrets.token_hex(32)

    rendered = _render_profile_env(
        profile=normalized_profile,
        openai_api_key=resolved_openai_key,
        origin=resolved_origin,
        jwt_secret=resolved_jwt_secret,
        api_key=resolved_api_key,
        ops_key=resolved_ops_key,
    )

    resolved_output.write_text(rendered, encoding="utf-8")
    return resolved_output


def _build_arg_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Generate a production env file from a DecisionDoc deployment profile template.",
    )
    parser.add_argument(
        "--profile",
        required=True,
        choices=sorted(PROFILE_TEMPLATES),
        help="Deployment profile to use as the base template.",
    )
    parser.add_argument(
        "--output",
        default=".env.prod",
        help="Output env file path. Default: .env.prod",
    )
    parser.add_argument(
        "--openai-api-key",
        default="",
        help="OpenAI API key. Falls back to OPENAI_API_KEY in the shell if omitted.",
    )
    parser.add_argument(
        "--origin",
        default="",
        help="Override ALLOWED_ORIGINS. Defaults to the profile's canonical domain.",
    )
    parser.add_argument(
        "--jwt-secret",
        default="",
        help="Override JWT_SECRET_KEY. Random value is generated by default.",
    )
    parser.add_argument(
        "--api-key",
        default="",
        help="Override DECISIONDOC_API_KEYS. Random value is generated by default.",
    )
    parser.add_argument(
        "--ops-key",
        default="",
        help="Override DECISIONDOC_OPS_KEY. Random value is generated by default.",
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="Overwrite the output file if it already exists.",
    )
    return parser


def main(argv: Sequence[str] | None = None) -> int:
    args = _build_arg_parser().parse_args(list(argv) if argv is not None else None)
    output_path = bootstrap_prod_env(
        profile=args.profile,
        output_file=Path(args.output),
        openai_api_key=args.openai_api_key,
        origin=args.origin,
        jwt_secret=args.jwt_secret,
        api_key=args.api_key,
        ops_key=args.ops_key,
        force=bool(args.force),
    )
    print(f"Generated prod env file: {output_path}")
    print(f"Profile: {args.profile}")
    print(f"Next: python3 scripts/check_prod_env.py --env-file {output_path} --expected-origin {args.origin.strip() or PROFILE_ORIGINS[args.profile]}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
