#!/usr/bin/env python3
"""Prepare a partially filled API key rotation change plan.

The script gathers the current git SHA and recent successful deploy-smoke runs,
then prints a Markdown plan that operators can paste into a change ticket or
save as a working note before the actual key rotation.
"""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
from pathlib import Path
from typing import Any


REPO_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_REPO = "sungjin9288/DecisionDoc-AI"


def _run(command: list[str], *, cwd: Path = REPO_ROOT) -> str:
    completed = subprocess.run(
        command,
        cwd=cwd,
        check=True,
        capture_output=True,
        text=True,
    )
    return completed.stdout.strip()


def _placeholder(value: str | None, fallback: str) -> str:
    if value and value.strip():
        return value.strip()
    return fallback


def _infer_repo_slug() -> str:
    try:
        remote_url = _run(["git", "remote", "get-url", "origin"])
    except subprocess.CalledProcessError:
        return DEFAULT_REPO

    normalized = remote_url.strip()
    if normalized.endswith(".git"):
        normalized = normalized[:-4]
    if normalized.startswith("git@github.com:"):
        return normalized.split(":", 1)[1]
    if normalized.startswith("https://github.com/"):
        return normalized.split("https://github.com/", 1)[1]
    return DEFAULT_REPO


def _get_head_sha() -> str:
    return _run(["git", "rev-parse", "HEAD"])


def _fetch_workflow_runs(repo_slug: str, *, per_page: int = 30) -> list[dict[str, Any]]:
    payload = _run(
        [
            "gh",
            "api",
            f"repos/{repo_slug}/actions/workflows/deploy-smoke.yml/runs?per_page={per_page}",
        ]
    )
    data = json.loads(payload)
    workflow_runs = data.get("workflow_runs")
    if not isinstance(workflow_runs, list):
        return []
    return [run for run in workflow_runs if isinstance(run, dict)]


def _stage_matches(run: dict[str, Any], stage: str) -> bool:
    title = str(run.get("display_title") or "")
    return f"deploy-smoke [{stage}]" in title


def _select_run_url(runs: list[dict[str, Any]], *, stage: str, head_sha: str) -> str:
    successful = [
        run for run in runs if run.get("conclusion") == "success" and _stage_matches(run, stage)
    ]
    if not successful:
        return "<RUN_ID_OR_URL>"

    for run in successful:
        if run.get("head_sha") == head_sha and run.get("html_url"):
            return str(run["html_url"])

    first = successful[0]
    html_url = first.get("html_url")
    if html_url:
        return str(html_url)
    run_id = first.get("id")
    if run_id:
        return str(run_id)
    return "<RUN_ID_OR_URL>"


def _render_plan(args: argparse.Namespace, *, repo_slug: str, head_sha: str, dev_run_url: str, prod_run_url: str) -> str:
    stage = args.stage
    stage_prod = "yes" if stage == "prod" else "no"

    return f"""# API Key Rotation Change Plan

Generated by `python3 scripts/prepare_api_key_rotation_change_plan.py --stage {stage}`

## 1. Change metadata

| 항목 | 값 |
|------|----|
| Change ticket / Incident | {_placeholder(args.ticket, "<TICKET_ID>")} |
| Change owner | {_placeholder(args.owner, "<OWNER_NAME>")} |
| Approver | {_placeholder(args.approver, "<APPROVER_NAME>")} |
| Change window start | {_placeholder(args.window_start, "<YYYY-MM-DD HH:MM KST>")} |
| Change window end | {_placeholder(args.window_end, "<YYYY-MM-DD HH:MM KST>")} |
| Target stage | {stage} |
| Old key label | {_placeholder(args.old_key_label, "<OLD_KEY_LABEL>")} |
| New key label | {_placeholder(args.new_key_label, "<NEW_KEY_LABEL>")} |
| Client rollout owner | {_placeholder(args.client_rollout_owner, "<CLIENT_OWNER>")} |
| Rollback owner | {_placeholder(args.rollback_owner, "<ROLLBACK_OWNER>")} |

## 2. Preconditions

- `prod` rotation인가: `{stage_prod}`
- Current repo: `{repo_slug}`
- Current `main` SHA가 실제 rollout 대상인지 확인
- 새 key 전달 대상과 old key 복구 경로 확인

| 체크 | 값 |
|------|----|
| Current `main` SHA | `{head_sha}` |
| Latest `deploy-smoke [dev]` run | {dev_run_url} |
| Latest `deploy-smoke [prod]` run | {prod_run_url} |
| OpenAI fallback 확인 | {_placeholder(args.openai_fallback, "yes / no")} |
| Client rollout 대상 목록 확인 | {_placeholder(args.client_rollout_ready, "yes / no")} |

## 3. Secret staging

1. `DECISIONDOC_API_KEYS=old,new`
2. `DECISIONDOC_API_KEY=old`

예시:

```bash
gh secret set DECISIONDOC_API_KEYS -R {repo_slug} --body "OLD_KEY,NEW_KEY"
gh secret set DECISIONDOC_API_KEY -R {repo_slug} --body "OLD_KEY"
```

## 4. Validation log

| 항목 | 값 |
|------|----|
| `deploy-smoke [dev]` rerun | `<RUN_ID_OR_URL>` |
| `Run smoke` | `success / fail` |
| `Run meeting recording smoke` | `success / fail` |
| `Run ops smoke` | `success / fail` |
| Caller cutover 방식 | `external-first / smoke-first` |
| `deploy-smoke [prod]` rerun | `<RUN_ID_OR_URL_OR_NA>` |

## 5. Finalize / Rollback

- finalize: `DECISIONDOC_API_KEYS=new` and `DECISIONDOC_API_KEY=new`
- rollback: `DECISIONDOC_API_KEYS=old` and `DECISIONDOC_API_KEY=old`

## 6. Closeout note

```text
API key rotation completed.
- Stage: {stage}
- Main SHA: {head_sha}
- Old key label: {_placeholder(args.old_key_label, "<OLD_KEY_LABEL>")}
- New key label: {_placeholder(args.new_key_label, "<NEW_KEY_LABEL>")}
- Dev validation run: <DEV_RUN_URL>
- Prod validation run: <PROD_RUN_URL_OR_NA>
- Finalize time: <TIME>
- Old key deleted: <YES_OR_NO>
- Owner: {_placeholder(args.owner, "<OWNER_NAME>")}
```
"""


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--stage", choices=("dev", "prod"), default="prod")
    parser.add_argument("--repo", default="", help="GitHub repo slug, e.g. owner/name")
    parser.add_argument("--ticket", default="")
    parser.add_argument("--owner", default="")
    parser.add_argument("--approver", default="")
    parser.add_argument("--window-start", default="")
    parser.add_argument("--window-end", default="")
    parser.add_argument("--old-key-label", default="")
    parser.add_argument("--new-key-label", default="")
    parser.add_argument("--client-rollout-owner", default="")
    parser.add_argument("--rollback-owner", default="")
    parser.add_argument("--openai-fallback", default="")
    parser.add_argument("--client-rollout-ready", default="")
    parser.add_argument("--output", default="", help="Write the plan to a file instead of stdout")
    return parser


def main(argv: list[str] | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)

    repo_slug = _placeholder(args.repo, _infer_repo_slug())
    try:
        head_sha = _get_head_sha()
        runs = _fetch_workflow_runs(repo_slug)
    except subprocess.CalledProcessError as exc:
        parser.exit(1, f"[prepare_api_key_rotation_change_plan] command failed: {exc}\n")
        return 1
    except json.JSONDecodeError as exc:
        parser.exit(1, f"[prepare_api_key_rotation_change_plan] invalid GitHub API payload: {exc}\n")
        return 1

    dev_run_url = _select_run_url(runs, stage="dev", head_sha=head_sha)
    prod_run_url = _select_run_url(runs, stage="prod", head_sha=head_sha)
    plan = _render_plan(
        args,
        repo_slug=repo_slug,
        head_sha=head_sha,
        dev_run_url=dev_run_url,
        prod_run_url=prod_run_url,
    )

    if args.output:
        output_path = Path(args.output)
        output_path.write_text(plan, encoding="utf-8")
        print(f"[prepare_api_key_rotation_change_plan] wrote plan to {output_path}", file=sys.stderr)
    else:
        print(plan)

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
